version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - frontend
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatbot

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - frontend/.env

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
